--DROP TABLE users IF EXISTS;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50),
  address VARCHAR(255),
  password VARCHAR(20),
  newsletter BOOLEAN,
  framework VARCHAR(500),
  sex VARCHAR(1),
  NUMBER INTEGER,
  COUNTRY VARCHAR(10),
  SKILL VARCHAR(500)
);
CREATE TABLE users2 (
  account VARCHAR(10) PRIMARY KEY,
  password VARCHAR(10),
  email VARCHAR(50),
  sex VARCHAR(4),
  name VARCHAR(10)
);

CREATE TABLE products (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  product_name VARCHAR(100),
  product_kinds VARCHAR(20),
  product_info VARCHAR(500),
  image VARCHAR(100)
);

CREATE TABLE order_info (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  product_id INTEGER,
  product_money VARCHAR(20),
  product_max_number INTEGER,
  state VARCHAR(20)
);

CREATE TABLE join_info (
  account VARCHAR(10),
  order_id INTEGER,
  product_number INTEGER
);
